stages:
  - unittests

variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  key: ${CI_JOB_NAME}
  paths:
    - .m2/repository

# Cancel pipeline if a newer pipeline is running
default:
  interruptible: true

###############################
#                             #
#     Unittests               #
#                             #
###############################

General:
  stage: unittests
  image: maven:3-jdk-11
  retry: 2
  services:
    - name: docker:23.0.5-dind
        # explicitly disable tls to avoid docker startup interruption
      command: [ "--tls=false" ]
  variables:
    # Instruct Testcontainers to use the daemon of DinD.
    DOCKER_HOST: "tcp://docker:2375"
    # Instruct Docker not to start over TLS.
    DOCKER_TLS_CERTDIR: ""
    # Improve performance with overlayfs.
    DOCKER_DRIVER: overlay2
  before_script:
    - 'mvn clean'
  script:
    - 'mvn $MAVEN_CLI_OPTS -Dtest="$TEST" test'
  parallel:
    matrix:
      - TEST: [
                # utility
                ODSFileParserTest,
                # iterator
                CSVIteratorTest, CSVWIteratorTest, ExcelIteratorTest, HTMLIteratorTest, JSONIteratorTest, ODSIteratorTest, XMLIteratorTest,
                # stream
                CSVStreamTest, CSVWStreamTest, ExcelStreamTest, JSONStreamTest, XMLStreamTest, ODSStreamTest,
                # general access
                DatabaseTest$$*, LocalAccessTest, SPARQLTest, WoTTest,
                # Flow
                CSVObservableTest, CSVWObservableTest, ExcelObservableTest, JSONObservableTest, ODSObservableTest, XMLObservableTest,
                # Serializability
                IteratorSerializabilityTest, StreamSerializabilityTest, ObservableSerializabilityTest
        ]
  except:
    - master
    - development